### ISSUE TITLE
Optional properties in UpdateProjectRequest

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/knora-api-js-lib#100]
Can we set all properties in UpdateProjectRequest class as optional. In my case I have to update project status only (restore deleted project) but keywords and description are needed. Or is there a reason for that?

**Comment by benjamingeer** [comment]
They're already optional in the sense that they can be empty collections. I think I suggested to @tobiasschweizer that if a collection can be empty, we could make the collection itself optional, but he said this would cause other problems. @tobiasschweizer is that right?

**Comment by benjamingeer** [comment]
Also, since the default values of these properties are [], you shouldn't have to specify them if you don't need them. What problem are you having?

**Comment by kilchenmann** [comment]
> They're already optional in the sense that they can be empty collections.

Not sure, my IDE says: "Type '{ status: true; }' is missing the following properties from type 'UpdateProjectRequest': keywords, description" when I want to update the project status only:

```typescript
const data: UpdateProjectRequest = {
    status: true
};
this.knoraApiConnection.admin.projectsEndpoint.updateProject(id, data).subscribe(
    (response: ApiResponseData<ProjectResponse>) => {
        // do something with the response
    }
);
```

And when we have a look on the builded definition file of type UpdateProjectRequest, keywords and description are not optional:

```typescript
/**
 * A request to update a project.
 */
export declare class UpdateProjectRequest {
    /**
     * Project keywords.
     */
    keywords: string[];
    /**
     * The path to the projects's logo.
     */
    logo?: string;
    /**
     * The longname of a Knora project.
     */
    longname?: string;
    /**
     * A description of a project.
     */
    description: StringLiteral[];
    /**
     * Exists and is true if users can add themselves to the project or group.
     */
    selfjoin?: boolean;
    /**
     * The unique shortname of a Knora project.
     */
    shortname?: string;
    /**
     * The status of the user / group / project. It is false if the entity has been deactivated (deleted).
     */
    status?: boolean;
}
```

By updating project status I don't want to send keywords or description. Even when they are empty, it will override the existing data?

**Comment by benjamingeer** [comment]
I think you have to do it like this:

```typescript
const data: UpdateProjectRequest = new UpdateProjectRequest();
data.status = true;
```
> Even when they are empty, it will override the existing data?

I don't know. Have you tried it?

**Comment by kilchenmann** [comment]
Thanks @benjamingeer. Yes it overrides the values. I tried your solution and this was the error response from Knora:
`{"error":"org.knora.webapi.InconsistentTriplestoreDataException: Project: http://rdfh.ch/projects/00FF has no description defined."}`

This means that the project description was overwritten with the empty value, which should not happen at all. Now, I'm not able to get all projects anymore, because of the missing description in the one project. 
Better would be to set keywords and description as optional in UpdateProjectRequest as I already mentioned.

**Comment by benjamingeer** [comment]
Thanks, OK, I’ll find a way to make them optional.

**Comment by musicEnfanthen** [comment]
Hey guys,

does the `updateProject` route expect a complete `data` = `UpdateProjectRequest` object?

@kilchenmann Could you try to fetch the data for the deleted project first and load it into your `data` variable, then to set `status` of this variable to `true`, and then use the complete `data` object for the `updateRequest`? (Probably two nested API calls with `switchMap` or something similar will be necessary to do so)

**Comment by subotic** [comment]
I've opened an issue https://github.com/dasch-swiss/knora-api/issues/1510 which is related to this one.

**Comment by kilchenmann** [comment]
@musicEnfanthen: 
> does the updateProject route expect a complete data = UpdateProjectRequest object?

not a complete object, but keywords and description are needed. I understand your solution, and I also thought about it, but it doesn't make sense to send more data than needed to reactivate a deleted project.

@subotic: Thank you.

**Comment by kilchenmann** [comment]
The simplest way would be — and thats what I had in the @knora/core module — an additional method to activate a project with the payload type `{status: true}`.
