### ISSUE TITLE
usersEndpoint: create or update user

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/knora-api-js-lib#107]
I'm not able to create a user (or update user). In the app we have a form to create new user and I submit for example the following data:

```json
{
  "email": "donald.duck@entenhausen.us",
  "familyName": "Duck",
  "givenName": "Donald",
  "lang": "en",
  "password": "DuckDuck50",
  "status": true,
  "systemAdmin": false,
  "username": "duck"
}
```

I get an error `400 Bad Request` with the message: "The request content was malformed:
Object is missing required member 'username'". I figured out, that the request payload is an empty object `{}`. It seems to be something's wrong in the `createUser` method in usersEndpoint. I have similar issues in `updateUserBasicInformation` or in projectsEndpoint. It always converts my payload data into an empty object. Probably because of `jsonConvert.serializeObject`?

**Comment by tobiasschweizer** [comment]
Could you point out to me how you use the method?

Or could you compare it to the unit tests: 

https://github.com/dasch-swiss/knora-api-js-lib/blob/ac1d0fe2bc4b299bb88118aefb175e2d5cf03454/src/api/admin/users/users-endpoint.spec.ts#L289-L369

The unit tests also check for the payload. Hence an empty object should make the tests fail.

**Comment by tobiasschweizer** [comment]
see #67 for a more convenient way to create instances

**Comment by kilchenmann** [comment]
I used the method as follow: 

```typescript
this.knoraApiConnection.admin.usersEndpoint.createUser(this.form.value).subscribe(
    (response: ApiResponseData<UserResponse>) => {
        this.user = response.body.user;
    },
    (error: ApiResponseError) => {
        this.errorMessage = error;
    }
);
```

But as #67 says, I have to initiate the data with `new User()` and allocate all properties with the form values? I'll try...

**Comment by kilchenmann** [comment]
So I have to write as follow:

```typescript
const userData: User = new User();
userData.username = this.form.value.username;
userData.familyName = this.form.value.familyName;
userData.givenName = this.form.value.givenName;
userData.email = this.form.value.email;
userData.password = this.form.value.password;
userData.systemAdmin = this.form.value.systemAdmin;
userData.status = this.form.value.status;
userData.lang = this.form.value.lang;

this.knoraApiConnection.admin.usersEndpoint.createUser(userData).subscribe(
    (response: ApiResponseData<UserResponse>) => {
        this.user = response.body.user;
    },
    (error: ApiResponseError) => {
        this.errorMessage = error;
    }
);
```

It's a little awkward, but ok. Thanks @tobiasschweizer

**Comment by tobiasschweizer** [comment]
> It's a little awkward

Yes, it is indeed inconvenient! 

We will try to come up with a better solution in #67
