### ISSUE TITLE
Update Test Angular App to version 8 

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-api-js-lib#123]
Update test framework Angular App to version ~~8~~9.

@flavens Could you give me  a hand here?

**Comment by flavens** [comment]
@tobiasschweizer yes I can help

**Comment by tobiasschweizer** [comment]
@flavens Could help me with that after my holiday?

**Comment by flavens** [comment]
> @flavens Could help me with that after my holiday?

yes sure just let me know
