### ISSUE TITLE
Missing label in ReadOntology

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/knora-api-js-lib#139]
Is it possible to extend the `ReadOntology` type with label from `rdfs:label`?

**Comment by tobiasschweizer** [comment]
Yes, this should be easy to do. Just add additional decorators to `ReadOntology` (https://github.com/dasch-swiss/knora-api-js-lib/blob/master/src/models/v2/ontologies/read-ontology.ts) and add some assertions to https://github.com/dasch-swiss/knora-api-js-lib/blob/324b84f4b1b63b6770f7d6dfa70c8f5c7b8c4088/src/api/v2/ontology/ontologies-endpoint.spec.ts#L56-L72

**Comment by kilchenmann** [comment]
@tobiasschweizer is there a reason why `classes` and `properties` in the `ReadOntology` are not an array? It is better to have an array that you can iterate over in the html template.

**Comment by tobiasschweizer** [comment]
The idea is that classes and properties can be accessed by their IRI. I think there could be an additional methods so you could get an array.

**Comment by kilchenmann** [comment]
Okay
