### ISSUE TITLE
Paging: Remove ForbiddenResource 

### ISSUE THREAD

**Issue by tobiasschweizer** [dasch-swiss/knora-api-js-lib#161]
https://github.com/dasch-swiss/knora-api/pull/1615 removes `ForbiddenResouce` from the results and introduces a new flag `knora-api:mayHaveMoreResults`.

knora-api-js-lib formats should be adapted.

@benjamingeer Can I get the required test data from https://github.com/dasch-swiss/knora-api/pull/1615?

**Comment by benjamingeer** [comment]
> Can I get the required test data from dasch-swiss/knora-api#1615?

I'll add a test response that includes `knora-api:mayHaveMoreResults`.

**Comment by tobiasschweizer** [comment]
Can a full resource request have this property too? In v2, you can request more than one resource.

**Comment by benjamingeer** [comment]
> Can a full resource request have this property too?

No, because there's no paging in that request.

**Comment by tobiasschweizer** [comment]
@benjamingeer  A search returns `ReadResource[]` (https://github.com/dasch-swiss/knora-api-js-lib/blob/03e74aec56d7d005b866e6f48ddf6b771fa280a0/src/api/v2/search/search-endpoint.ts#L125).

So currently there is no way to put the information that there are possibly more results. Of course, I could change the signature, wrapping the result array in an object, but this would not be backwards compatible.

I have an idea how to this, but I would have to try it out first. Maybe I could define a subclass of the standard array and just add a property to it (see https://blog.simontest.net/extend-array-with-typescript-965cc1134b3).

**Comment by tobiasschweizer** [comment]
I think something like this would be possible:

```
class MyArray<ReadResource> extends Array<ReadResource> {
    mayHaveMoreResults: boolean = false;

    constructor(items?: Array<ReadResource>) {
        super(...items);
        Object.setPrototypeOf(this, Object.create(MyArray.prototype));
    }
}
```

But it requires the compiler option `"downlevelIteration" : true` and I do not understand yet what this implies.

**Comment by benjamingeer** [comment]
I think it would be clearer to wrap the result array in an object.

**Comment by tobiasschweizer** [comment]
yes, but this would be a incompatible change in the public API. And I am not sure how to deal with that (notification, release etc.).

**Comment by benjamingeer** [comment]
The whole thing is in alpha, right? It's not expected to be stable. I think you can change whatever you want. You can use Discuss DaSCH for the notification.

**Comment by tobiasschweizer** [comment]
>You can use Discuss DaSCH for the notification.

I thought we do not use it anymore, but Google Drive instead.

**Comment by benjamingeer** [comment]
> I thought we do not use it anymore, but Google Drive instead.

@subotic ?

**Comment by benjamingeer** [comment]
> Can I get the required test data from dasch-swiss/knora-api#1615?

Done in https://github.com/dasch-swiss/knora-api/pull/1615/commits/40fa1845314f7ef96e41d60fd62c31525525ffab.

**Comment by tobiasschweizer** [comment]
@benjamingeer Ok I described the planned change in https://github.com/dasch-swiss/knora-proposals/blob/master/designs/2020-03-23-knora-api-lib-js-paging.md. 

I will create a PR this week.

**Comment by benjamingeer** [comment]
Can https://github.com/dasch-swiss/knora-api/pull/1615 be merged before this issue is resolved?

**Comment by tobiasschweizer** [comment]
> Can [dasch-swiss/knora-api#1615](https://github.com/dasch-swiss/knora-api/pull/1615) be merged before this issue is resolved?

I would rather prepare the related PR first. This will happen this week. Would that be ok?

**Comment by benjamingeer** [comment]
OK no problem.
