### ISSUE TITLE
Missing methods: Get all ontologies

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/knora-api-js-lib#88]
In the extended search (@knora/search) we use the following method:

```typescript
this._cacheService.getOntologiesMetadata().subscribe(
    (ontologies: Array<OntologyMetadata>) => {
        this.ontologies = ontologies;
    }
);
```

I couldn't find an equivalent method in the knora-api-js-lib to get all ontologies.

**Comment by tobiasschweizer** [comment]
I will add it to `src/api/v2/ontology/ontologies-endpoint.ts`.
