### ISSUE TITLE
Authentication endpoint: login by username or email address

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/knora-api-js-lib#89]
As I saw it's only possible to login by username, not by email address. Can you expand the login method to support both?

In @knora/authentication we handled it as follow:

```typescript
login(identifier: string, password: string): Observable<string> {
        let params: AuthenticationRequestByUsernamePayload | AuthenticationRequestByEmailPayload;

        // username can be either name or email address, so what do we have?
        if (identifier.indexOf('@') > -1) {
            // username is email address
            params = { email: identifier, password: password };
        } else {
            params = { username: identifier, password: password };
        }

        return this.httpPost(this.path, params).pipe(
            map((result: ApiServiceResult) => result.getBody(AuthenticationResponse).token),
            catchError(this.handleJsonError)
        );
    }
```

**Comment by kilchenmann** [comment]
The authentication is a combination of a identifier and password. The user identifier can be one of the following:
- the user’s IRI,
- the user’s Email, or
- the user’s Username.

The login method and the login form in @knora/authentication module supported the two identifiers email or username by using the mentioned code above. 
It's 
`POST: v2/authentication` and the params are either
- `{ email: identifier, password: password }` or 
- `{ username: identifier, password: password }`

**Comment by benjamingeer** [comment]
This isn't part of the generated code and I don't know where it's implemented. Reassigning to @tobiasschweizer.

**Comment by tobiasschweizer** [comment]
I will implement that in `src/api/v2/authentication/authentication-endpoint.ts`.
