### ISSUE TITLE
Users endpoint: activate user is missing

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/knora-api-js-lib#91]
I couldn't find a method to reactivate a deleted user.

**Comment by kilchenmann** [comment]
@benjamingeer Can you add a method to update user's status from false to true? It's the following user operation: 

`PUT: /admin/users/iri/<userIri>/Status` 

Documented here: https://docs.knora.org/paradox/03-apis/api-admin/users.html

**Comment by benjamingeer** [comment]
This is `updateUserStatus`:

https://github.com/dasch-swiss/knora-api-js-lib/blob/22d7c570e3ac852a715a58c4039f31914bc5bf14/src/api/admin/users/users-endpoint.ts#L158

**Comment by kilchenmann** [comment]
@benjamingeer Tank you!
